# SPDX-License-Identifier: Apache-2.0
# West yml manifest for Zephyr dom0 demo

manifest:
  remotes:
    - name: nexec_zephyr_dom0
      url-base: https://github.com/nexec/

  projects:
    - name: zephyr
      remote: nexec_zephyr_dom0
      revision: v3.1.0_xendom0
      west-commands: scripts/west-commands.yml

