# SPDX-License-Identifier: Apache-2.0
# West yml manifest for Zephyr as Xen dom0

manifest:
  self:
    path: xenutils

  remotes:
    - name: sakib
      url-base: https://github.com/sa-kib/
    - name: firscity
      url-base: https://github.com/firscity/
    - name: dsemenets
      url-base: https://github.com/dsemenets/
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
    - name: xentroops
      url-base: https://github.com/xen-troops/

  projects:
    - name: zephyr
      remote: firscity
      revision: zephyr_aos_porting
      west-commands: scripts/west-commands.yml
    - name: xen
      remote: xentroops
      revision: xen-4.17rc-migration
    - name: littlefs
      remote: zephyr
      path: modules/fs/littlefs
      groups:
        - fs
      revision: ca583fd297ceb48bced3c2548600dc615d67af24
