# SPDX-License-Identifier: Apache-2.0
# West yml manifest for Zephyr as Xen dom0

manifest:
  self:
    path: xenutils

  remotes:
    - name: sakib
      url-base: https://github.com/sa-kib/
    - name: firscity
      url-base: https://github.com/firscity/

  projects:
    - name: zephyr
      remote: sakib
      revision: dom0_devel
      west-commands: scripts/west-commands.yml
    - name: xen
      remote: firscity
      revision: master
